### ISSUE TITLE
What's the purpose of selfDetermined?

### ISSUE THREAD

**Issue by shuizaiku7** [MikePopoloski/slang#316]
// Perform type propagation and constant folding of a self-determined subexpression.
void Expression::selfDetermined(const BindContext& context, Expression*& expr) {
        ASSERT(expr->type);
        PropagationVisitor visitor(context, *expr->type);
        expr = &expr->visit(visitor);
}

PropagationVisitor(const BindContext& context, const Type& newType) :
        context(context), newType(newType) {}
bool needConversion = !newType.isEquivalent(*expr.type);

Every time selfDetemined is called, newType always equals to *expr.type, and selfDetemined will do nothing.
So, colud you please explain what's the purpose of this method?

**Comment by MikePopoloski** [comment]
You're right that it doesn't change the type of the root of the expression tree, but it does continue to propagate that type down to context-determined subexpressions, which may have a different type. Type propagation requires knowing the types of all operands in order to figure out their actual final types, which is why this is a second pass after the expression tree has been created.
