### ISSUE TITLE
Compiler indicator statements are not supported

### ISSUE THREAD

**Issue by YJT13845** [MikePopoloski/slang#458]
The synopsys translate_off and synopsys translate_on are not supported.
example:
![image](https://user-images.githubusercontent.com/40222068/134513116-d710af19-cd8b-420a-9a86-4479895ae334.png)

**Comment by MikePopoloski** [comment]
Yes, slang is not built by synopsys. Also putting directives to the compiler inside comments is pretty much the worst idea I've ever seen implemented in a programming language and I have no desire to perpetuate it. This problem is easily solved with an ifdef or a conditional generate instead, and it will make your code portable to all tools instead of being tied to a single one.

**Comment by YJT13845** [comment]
You have a point there. Thank you for your reply!
