### ISSUE TITLE
Module declaration parsing discards attributes

### ISSUE THREAD

**Issue by paulsc96** [MikePopoloski/slang#625]
When parsing the syntax of a module, for example using `SyntaxTree::fromText()` or `SyntaxRewriter::parse()`, its attributes are ignored and not part of the resulting syntax node.

## Minimal example

```C++
    SourceManager sm;
    auto tree = SyntaxTree::fromText("(* myattrib *) module dummy(); endmodule", sm);
    auto &modDecl = tree->root().as<ModuleDeclarationSyntax>();
    fmt::print("Stringified syntax: {}\n", modDecl.toString());
    fmt::print("Attributes empty: {}\n", modDecl.attributes.empty());
```

produces

```
Stringified syntax:  module dummy(); endmodule
Attributes empty: true
```

i.e. the attribute `myattrib` is lost and the `attributes` syntax list has no elements.

**Comment by MikePopoloski** [comment]
Fixed in da0576d9c01fb2c9493eb284592e5e88bcdf08a1

SyntaxTree::fromText uses Parser::parseGuess, so it's always going to have holes in how it handles things. If you have a full valid compilation unit in your string you can use SyntaxTree::fromFileInMemory instead to be sure things work exactly correctly. This particular case was easy enough to fix though so I did.
