### ISSUE TITLE
Compilation instance destructor triggers SIGABRT

### ISSUE THREAD

**Issue by apatern0** [MikePopoloski/slang#634]
**Describe the bug**
When instantiating Compilation, its destructor fails with SIGABRT.

**To Reproduce**
Simply compile and run the following:

```
#include <slang/ast/Compilation.h>
int main (void) {
     slang::ast::Compilation c;
}
```

I'm building against commit "76680b3a963d3c3ea8190327686b1c611e65f978", on MacOS.

Steps used to build library:
```
cmake -B build -DSLANG_INCLUDE_DOCS=ON -DBUILD_SHARED_LIBS=OFF -DSLANG_INCLUDE_TESTS=OFF  -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_BUILD_TYPE=Debug
cmake --build build
cmake --install build
```

Then to build the executable and test it:
```
>>> g++ -g3 -lslang -std=c++17 -I../slang/build/source/ test.cpp -o test
>>> ./test
[1]    88338 abort      ./test
>>>
```

Using clang:
```
>>> g++ --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by MikePopoloski** [comment]
This is not enough info to reproduce; there are thousands of tests in the library that exercise code exactly like this; you need to provide more info about how you're building and linking the library into your program.

**Comment by apatern0** [comment]
> This is not enough info to reproduce; there are thousands of tests in the library that exercise code exactly like this; you need to provide more info about how you're building and linking the library into your program.

You're right, I extended the message above with more information.

Thanks!

**Comment by MikePopoloski** [comment]
It's not enough to just manually link to the library, because if you don't get compilation and linking flags correct you'll have exactly the problem you're experiencing (for example, linking to the debug version of the library requires the `DEBUG` define be set when including slang headers or else you'll get an ABI mismatch.

You might be able to get away with just adding a `-DDEBUG` to your build for now, but to be robust you need to get the full set of flags from cmake by using cmake yourself, or probably something like pkgconfig if you don't want to use cmake.

**Comment by apatern0** [comment]
Thanks, using -DDEBUG indeed solves the problem (and others I've been experiencing).

As for CMake, I didn't know it would be necessary, but of course, I can try and implement it. Is there a minimum working example of how such a CMakeLists.txt would look like?

Thanks again!

**Comment by MikePopoloski** [comment]
It's on my TODO list to make some examples and write some documentation on integrating the library but haven't done that yet. I'll try to get to it soon though.
