### ISSUE TITLE
what APIs or instructions could I use to generat code using slang

### ISSUE THREAD

**Issue by fzwwj95** [MikePopoloski/slang#667]
> The parse tree should round trip back to the original source
> SystemVerilog code generation and refactoring

Are there APIs or commands that can be used directly to parse AST in JSON format or to transform json back to the source code？
Sorry, I didn't find any relevant information in the API document. Could you give me some relevant tips?
If I need to write scripts to achieve this, what APIs or instructions can I use?

**Comment by MikePopoloski** [comment]
The JSON output is not currently parseable by the slang library. Such a feature could be added though.

The notes you quoted are for the parser tree (or alternatively named "concrete" syntax tree) which can round trip to source code and can be modified programmatically to do code generation. The "abstract" syntax tree isn't necessarily round trippable to source code because it's been made abstract, so things like implicit types have been filled in, different syntactical forms for representing things like ansi vs non-ansi ports have been unified, etc.
