### ISSUE TITLE
Controlling slang-tidy warnings/errors?

### ISSUE THREAD

**Issue by jrudess** [MikePopoloski/slang#808]
Is their any documentation for slang-tidy on how to control it?  There is a rule called EnforcePortSuffix that is requiring all input ports and output ports follow a naming convention that I've never run across in the industry before, so I want to fully disable this check, otherwise it spams out hundreds of thousands of warnings which overflow most peoples terminal buffer sizes.

```
    port 'name' is not correctly suffixed with suffix: _o
    port 'name' is not correctly suffixed with suffix: _i
```

The rule EnforceModulePrefix also has a mistake in the message it prints as it uses the word "port" instead of either "module" or "interface" depending on which type the rule is flagging the warning for.  It also says "suffix" instead of "prefix".

```
   file:100:16: warning: port 'modulename' is not correctly suffixed with suffix: i_
        moduletype modulename(
```

**Comment by Sustrak** [comment]
Hi @jrudess, you can control which checks are enabled by using a `.slang-tidy` file. This file can be provided using the `--config-file` argument or the slang-tidy tool will search for it from the path where it has been called until the root directory.

If you want to disable the `EnforcePortSuffix` check the contents of the file shoud be:

```
Checks:
    -ports-enforce-port-suffix
```

Putting a `-` before the name of the check disables it. I'll try to improve the documentation in this part since it is pretty vague.

I'll also do a MR that fixes the errors on the message for the `EnforceModulePrefix`. Thanks for the catch 😄
